name: Check URLs ðŸ”—

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, devel]

jobs:
  links:
    name: Validate Links ðŸ•¸ï¸
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.commits[0].message, '[skip links]')
    steps:
      - uses: actions/checkout@v3

      - name: Check URLs in docs ðŸ“‘
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          fail: true
          jobSummary: true
          format: markdown
          output: links-results.md
          args: >-
            --exclude-private
            --exclude "https://github.com.*.git|lycheeverse.*"
            --verbose
            --no-progress
            ${{ inputs.additional_args }}
            **/*.md
            **/*.html
            **/*.Rmd
            **/*.yaml
            **/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
