---
name: Check Spelling ðŸ†Ž

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: spelling-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  spelling:
    name: Run Spellcheck ðŸ” 
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.commits[0].message, '[skip spellcheck]')
    steps:
      - name: Checkout repository ðŸ›Ž
        uses: actions/checkout@v4

      - name: Setup R ðŸ“Š
        uses: r-lib/actions/setup-r@v2

      - name: Install R package dependencies ðŸ“¦
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::spelling

      - name: Run Spellcheck ðŸ‘Ÿ
        uses: insightsengineering/r-spellcheck-action@v3
        with:
          exclude: data/*,**/*.Rd,**/*.md,*.md
          additional_options: ""
  spellcheck_admiral:
    name: Spelling (admiral)
    uses: pharmaverse/admiralci/.github/workflows/spellcheck.yml@main
    if: github.event_name == 'pull_request'
    with:
      r-version: "release"
