---
name: Check Spelling ğŸ†

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: spelling-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  spelling:
    name: Run Spellcheck ğŸ” 
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.commits[0].message, '[skip spellcheck]')
        && github.event.pull_request.draft == false
    steps:
      - name: Checkout repository ğŸ›
        uses: actions/checkout@v4

      - name: Setup R ğŸ“Š
        uses: r-lib/actions/setup-r@v2

      - name: Install R package dependencies ğŸ“¦
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::spelling

      - name: Run Spellcheck ğŸ‘Ÿ
        uses: insightsengineering/r-spellcheck-action@v3
        with:
          exclude: data/*,**/*.Rd,**/*.md,*.md
          additional_options: ""
